import re
import sys
from pathlib import Path

REPLACEMENTS = [
    ("FRIDA", "PENGU"),
    ("Frida", "Pengu"),
    ("frida", "pengu"),
]

# These exact identifiers are generated by frida-core's top-level meson.build
# (cdata.set(...) / --define=...) and therefore live outside the source tree
# this script rewrites. Any Vala/C reference to them (Config.FRIDA_LIBDIR,
# #if HAVE_FRIDA_GLIB, etc.) must keep matching the meson-generated name
# exactly, so they're protected from the general substitution below.
PROTECTED_TOKENS = [
    "FRIDA_VERSION",
    "FRIDA_MAJOR_VERSION",
    "FRIDA_MINOR_VERSION",
    "FRIDA_MICRO_VERSION",
    "FRIDA_NANO_VERSION",
    "FRIDA_PREFIX",
    "FRIDA_LIBDIR_NAME",
    "FRIDA_LIBDIR",
    "FRIDA_HELPER_NAME",
    "FRIDA_AGENT_NAME",
    "FRIDA_COMPILER_BACKEND_NAME",
    "HAVE_FRIDA_GLIB",
    # Static headers referenced by their literal on-disk filename from
    # meson.build (files(...)) and/or .vapi (cheader_filename = "..."):
    # this script doesn't rename filenames, only file content, so any
    # #include/cheader_filename spelling of these must stay unchanged
    # too or the compiler can't find the (still frida-*-named) file.
    "frida-atomics.h",
    "frida-darwin.h",
    "frida-jni.h",
    "frida-linux-bpf.h",
    "frida-linux-perf-event.h",
    "frida-tvos.h",
    "frida-selinux.h",
    "frida-helper-service-glue.h",
    "frida-helper-process-glue.h",
]
# Longest-first so e.g. FRIDA_LIBDIR_NAME is protected whole rather than
# leaving a dangling _NAME after FRIDA_LIBDIR matches first.
PROTECTED_TOKENS.sort(key=len, reverse=True)
_PLACEHOLDER_FMT = "\x00PROTECTED_TOKEN_{}\x00"


def protect_and_replace(text: str) -> str:
    saved = []

    def stash(match: re.Match) -> str:
        saved.append(match.group(0))
        return _PLACEHOLDER_FMT.format(len(saved) - 1)

    protect_re = re.compile("|".join(re.escape(t) for t in PROTECTED_TOKENS))
    text = protect_re.sub(stash, text)

    for old, new in REPLACEMENTS:
        text = text.replace(old, new)

    for i, original in enumerate(saved):
        text = text.replace(_PLACEHOLDER_FMT.format(i), original)

    return text

# Only real source files get text-substituted. meson.build / meson_options.txt /
# .wrap files are deliberately excluded: they reference subproject and
# dependency names (e.g. subproject('frida-gum'), dependency('frida-gum-1.0'))
# that must keep matching the actual on-disk directory names, which this
# script does NOT rename. Renaming those identifiers without also renaming
# directories would break meson's subproject resolution.
SOURCE_SUFFIXES = {".vala", ".vapi", ".c", ".h", ".cpp", ".cc", ".hpp", ".m", ".mm", ".java"}
EXTRA_EXACT_NAMES = {"Makefile"}

EXCLUDE_DIR_NAMES = {".git", "releng", "deps", "build", "toolchain"}


# Thin .vapi bindings straight onto static, un-renamed headers
# (frida-linux-bpf.h, frida-atomics.h, frida-darwin.h, frida-jni.h, ...).
# Most of their consts/enums have no explicit cname/cprefix, so Vala
# derives the expected C symbol name from the enclosing `namespace Frida`
# by convention - renaming that namespace would silently break every
# such implicit binding (e.g. BPF_RINGBUF_HEADER_SIZE would start
# looking for PENGU_BPF_RINGBUF_HEADER_SIZE, which doesn't exist).
# These files are pure C interop plumbing with no runtime-visible
# strings of their own, so excluding them entirely is both safe and low
# value to rename in the first place.
EXCLUDE_RELATIVE_FILES = {
    "lib/base/frida-linux.vapi",
    "lib/base/frida-atomics.vapi",
    "vapi/darwin-gcd.vapi",
    "vapi/darwin-xpc.vapi",
    "vapi/jni.vapi",
    "lib/payload/libc-shim.vapi",
}


def should_process(path: Path, core_root: Path) -> bool:
    if any(part in EXCLUDE_DIR_NAMES for part in path.parts):
        return False
    try:
        rel = path.relative_to(core_root).as_posix()
    except ValueError:
        rel = path.as_posix()
    if rel in EXCLUDE_RELATIVE_FILES:
        return False
    if path.suffix in SOURCE_SUFFIXES:
        return True
    if path.name in EXTRA_EXACT_NAMES:
        return True
    return False


def rename_java_package_dir(core_root: Path):
    old_dir = core_root / "src" / "android-helper" / "re" / "frida"
    new_dir = core_root / "src" / "android-helper" / "re" / "pengu"
    if old_dir.is_dir():
        new_dir.parent.mkdir(parents=True, exist_ok=True)
        old_dir.rename(new_dir)
        print(f"[*] moved {old_dir} -> {new_dir}")
    else:
        print(f"[*] no android-helper java package dir at {old_dir}, skipping move")


def rename_text_in_tree(root: Path) -> int:
    total = 0
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if not should_process(path, root):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        new_text = protect_and_replace(text)
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            n = sum(text.count(old) for old, _ in REPLACEMENTS)
            total += n
            print(f"[*] {path}: {n} replacement(s)")
    return total


def main(argv):
    if len(argv) != 2:
        print(f"Usage: {argv[0]} <frida-core-dir>", file=sys.stderr)
        return 2

    core_root = Path(argv[1])
    if not core_root.is_dir():
        print(f"{core_root}: not a directory", file=sys.stderr)
        return 1

    rename_java_package_dir(core_root)
    total = rename_text_in_tree(core_root)
    print(f"[*] total replacements: {total}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
